version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region ap-south-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd  audit-checklist
      - mvn clean package
      - docker build -t ij023-pod2-checklist-registry:latest .
      - docker tag ij023-pod2-checklist-registry:latest 299629158582.dkr.ecr.ap-south-1.amazonaws.com/ij023-pod2-checklist-registry:ij023-pod2-checklistapp

  post_build:
    commands:
      - echo "Post_build"
      - docker push 299629158582.dkr.ecr.ap-south-1.amazonaws.com/ij023-pod2-checklist-registry:ij023-pod2-checklistapp
      - printf '[{"name":"ij023-pod2-checklistapp-container","imageUri":"%s"}]' 299629158582.dkr.ecr.ap-south-1.amazonaws.com/ij023-pod2-checklist-registry:ij023-pod2-checklistapp > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - audit-checklist/taskdefinition.json